open_manipulator_6dof:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
  
  # Effort Controllers ---------------------------------------     
  joint1_effort:
    type: effort_controllers/JointEffortController
    joint: joint1
  joint2_effort:
    type: effort_controllers/JointEffortController
    joint: joint2
  joint3_effort:
    type: effort_controllers/JointEffortController
    joint: joint3
  joint4_effort:
    type: effort_controllers/JointEffortController
    joint: joint4
  joint5_effort:
    type: effort_controllers/JointEffortController
    joint: joint5
  joint6_effort:
    type: effort_controllers/JointEffortController
    joint: joint6
  
  gripper_position:
    type: position_controllers/JointPositionController
    joint: gripper

  gripper_sub_position:
    type: position_controllers/JointPositionController
    joint: gripper_sub